apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocdeu   #eu=europe
  namespace: argocdmanager
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'